openapi: 3.0.0
info:
  title: Raffle Service API
  version: 1.0.0

paths:
  /startup:
    get:
      summary: Get startup configuration
      responses:
        '200':
          description: Startup configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartupResponse'

  /info/blockchain:
    get:
      summary: Get service information
      responses:
        '200':
          description: Service info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoBlockchainResponse'

  /raffle:
    get:
      summary: Get raffle summaries
      parameters:
        - in: query
          name: offset
          schema:
            type: number
            default: 0
        - in: query
          name: limit
          schema:
            type: number
            default: 10
        - in: query
          name: status
          schema:
            type: array
            items:
              type: string
              enum: [active, successful, failed]
          style: form
          explode: false
        - in: query
          name: tokenIds
          schema:
            type: array
            items:
              type: string
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
        - in: query
          name: ids
          schema:
            type: array
            items:
              type: string
        - in: query
          name: text
          schema:
            type: string
        - in: query
          name: direction
          schema:
            type: string
            enum: [ASC, DESC]
        - in: query
          name: order
          schema:
            type: string
            enum: [height, deadline]
      responses:
        '200':
          description: Raffle list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaffleSummaryResponse'
  /raffle/{raffleId}:
    get:
      summary: Get raffle details by ID
      parameters:
        - in: path
          name: raffleId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Raffle details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaffleDetailResponse'
        '404':
          description: Raffle not found
  /raffles/{raffleId}/winner-baskets:
    get:
      summary: Get winner baskets of a raffle
      parameters:
        - in: path
          name: raffleId
          required: true
          schema:
            type: string

        - in: query
          name: offset
          schema:
            type: integer
            default: 0

        - in: query
          name: limit
          schema:
            type: integer
            default: 20

        - in: query
          name: type
          schema:
            type: string
            enum: [share, empty, gift, share_gift]
          description: Basket filter type

      responses:
        '200':
          description: Winner baskets list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WinnerBasketListResponse'

        '404':
          description: Raffle not found
  /activities:
    get:
      summary: Get activities
      parameters:
        - in: query
          name: raffleId
          schema:
            type: string

        - in: query
          name: offset
          schema:
            type: integer
            default: 0

        - in: query
          name: limit
          schema:
            type: integer
            default: 10

        - in: query
          name: type
          description: Filter activity types
          schema:
            type: string
            enum: [raffle_created, ticket_bought, voted, gift_added]
          style: form
          explode: false

        - in: query
          name: address
          description: Return only activities of the caller
          schema:
            type: string

      responses:
        '200':
          description: Raffle activities
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaffleActivityResponse'
  /raffles/{raffleId}/winner-baskets/{basketId}:
    get:
      summary: Get details of a winner basket
      parameters:
        - in: path
          name: raffleId
          required: true
          schema:
            type: string
        - in: path
          name: basketId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Winner basket details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WinnerBasketDetailResponse'
        '404':
          description: Basket not found
components:
  schemas:
    #######################
    # Startup
    #######################
    StartupResponse:
      type: object
      properties:
        txFee:
          type: integer
          x-faker: 150000
        version:
          type: string
          x-faker: '1.0.0'
        verifiedTokens:
          type: array
          items:
            $ref: '#/components/schemas/VerifiedToken'
      required: [txFee, version, verifiedTokens]

    VerifiedToken:
      type: object
      properties:
        tokenId:
          type: string
          x-faker: b2dcea48caf0e73309138d659f6eb69d7ec8793dee989670c72dd4ffde7ebeb3
        name:
          type: string
          x-faker: rsBTC
      required: [tokenId, name]

    #######################
    # Blockchain Info
    #######################
    InfoBlockchainResponse:
      type: object
      properties:
        fee:
          type: object
          properties:
            tx:
              type: integer
              format: int64
            service:
              type: number
            implementer:
              type: number
            creation:
              type: integer
              format: int64
          required:
            - tx
            - service
            - implementer
            - creation
        height:
          type: number
      required:
        - fee
        - height

    #######################
    # Raffles
    #######################
    RaffleSummaryResponse:
      type: object
      properties:
        total:
          type: integer
          minimum: 1
          maximum: 1000
          x-faker: 23
        items:
          type: array
          items:
            $ref: '#/components/schemas/RaffleSummary'
      required: [total, items]

    RaffleSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        picture:
          type: string
        token:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            decimals:
              type: number
              default: 0
            verified:
              type: boolean
          required: [id, name, decimals, verified]
        winnersCount:
          type: number
        giftCount:
          type: number
        tags:
          type: array
          items:
            type: string
        deadline:
          type: number
        amount:
          type: object
          properties:
            goal:
              type: integer
              format: int64
            raised:
              type: integer
              format: int64
          required: [goal, raised]
        ticketPrice:
          type: integer
          format: int64
        status:
          type: string
          enum: [active, successful, failed]
      required:
        - id
        - name
        - description
        - token
        - winnersCount
        - giftCount
        - deadline
        - amount
        - ticketPrice
        - status
    #######################
    # Raffle Detail
    #######################

    RaffleDetailResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        token:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            decimals:
              type: number
              default: 0
            verified:
              type: boolean
          required: [id, name, decimals, verified]
        tags:
          type: array
          items:
            type: string
        pictures:
          type: array
          items:
            type: string
        giftCount:
          type: number
        winnersCount:
          type: number
        ticketPrice:
          type: integer
          format: int64
        deadline:
          type: number
        amount:
          type: object
          properties:
            goal:
              type: integer
              format: int64
            raised:
              type: integer
              format: int64
          required: [goal, raised]
        addresses:
          type: object
          properties:
            project:
              type: string
            implementer:
              type: string
            service:
              type: string
          required: [project, implementer, service]
        share:
          type: object
          properties:
            winner:
              type: number
            implementer:
              type: number
            service:
              type: number
          required: [winner, implementer, service]
        backers:
          type: number
        status:
          type: string
          enum: [active, successful, failed]
      required:
        - id
        - name
        - description
        - token
        - winnersCount
        - giftCount
        - deadline
        - amount
        - ticketPrice
        - status
        - pictures
        - addresses
        - share
        - backers
    RafflePrize:
      type: object
      properties:
        prizeId:
          type: string
        name:
          type: string
        image:
          type: string
          format: uri
        amount:
          type: integer
      required:
        - prizeId
        - name

    
    #######################
    # Winner Baskets
    #######################
    WinnerBasketListResponse:
      type: object
      properties:
        total:
          type: integer
          minimum: 1
          maximum: 1000
          x-faker: 23
        items:
          type: array
          items:
            $ref: '#/components/schemas/WinnerBasket'
      required:
        - total
        - items

    WinnerBasket:
      type: object
      properties:
        basketId:
          type: string
        type:
          type: string
          enum: [empty, shared]
        shareAmount:
          type: number
          description: Calculated share amount
        sharePercent:
          type: number
          description: Calculated share percent
        gifts:
          type: array
          items:
            $ref: '#/components/schemas/BasketGiftSimple'
      required:
        - basketId
        - type
        - gifts
    #######################
    # Basket Gift
    #######################
    BasketGift:
      type: object
      properties:
        id:
          type: string
          description: Gift Id
        basketId:
          type: string
          description: Basket Id
        assets:
          type: array
          items:
            $ref: '#/components/schemas/GiftAsset'
      required:
        - id
        - basketId
        - assets
    
    #######################
    # Gift Asset
    #######################
    GiftAsset:
      type: object
      properties:
        tokenId:
          type: string
          description: Token Id
        tokenName:
          type: string
          description: Token Name
        amount:
          type: number
          description: Amount
      required:
        - tokenId
        - amount
    BasketGiftSimple:
      type: object
      properties:
        asset:
          type: string
        amount:
          type: number
        verified:
          type: boolean
      required:
        - asset
        - amount
        - verified

    #######################
    # Winner Basket Detail
    #######################
    WinnerBasketDetailResponse:
      type: object
      properties:
        basketId:
          type: string
        type:
          type: string
          enum: [empty, shared]
        tokenId:
          type: string
        tokenName:
          type: string
        sharePercent:
          type: number
          format: float
        shareAmount:
          type: number
        gifts:
          type: array
          items:
            $ref: '#/components/schemas/BasketGiftDetail'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/BasketTransaction'
      required:
        - basketId
        - type
        - gifts
        - transactions
        - tokenId
        - tokenName

    BasketGiftDetail:
      type: object
      properties:
        id:
          type: string
        basketId:
          type: string
        assets:
          type: array
          items:
            $ref: '#/components/schemas/GiftAsset'
        verified:
          type: boolean
      required:
        - id
        - assets
        - verified

    BasketTransaction:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [asset_unwrap, ticket_won, asset_added]
        amount:
          type: number
        wallet:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - type
        - amount
        - wallet
        - address
        - createdAt

    #######################
    # Raffle Activity
    #######################
    RaffleActivityResponse:
      type: object
      properties:
        total:
          type: integer
          minimum: 1
          maximum: 1000
          x-faker: 23
        items:
          type: array
          items:
            $ref: '#/components/schemas/RaffleActivity'
      required:
        - total
        - items

    RaffleActivity:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - raffle_created
            - ticket_bought
            - upvoted
            - downvoted
            - basket_won
            - gift_added
            - raising_money
        status:
          type: string
          enum:
            - successful
            - pending
            - canceled
        address:
          type: string
        amount:
          type: number
          nullable: true
        basketNumber:
          type: string
          nullable: true
        basketType:
          type: string
        raffleName:
          type: string
          nullable: true
        raffleId:
          type: string
        createdAt:
          type: integer
      required:
        - id
        - type
        - address
        - createdAt