/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Raffle Service API
 * OpenAPI spec version: 1.0.0
 */
import { httpClient } from './http';
export interface StartupResponse {
  txFee: number;
  version: string;
  verifiedTokens: VerifiedToken[];
}

export interface VerifiedToken {
  tokenId: string;
  name: string;
}

export type InfoBlockchainResponseFee = {
  tx: number;
  service: number;
  implementer: number;
  creation: number;
};

export interface InfoBlockchainResponse {
  fee: InfoBlockchainResponseFee;
  height: number;
}

export interface RaffleSummaryResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: RaffleSummary[];
}

export type RaffleSummaryToken = {
  id: string;
  name: string;
  decimals: number;
  verified: boolean;
};

export type RaffleSummaryAmount = {
  goal: number;
  raised: number;
};

export type RaffleSummaryStatus = (typeof RaffleSummaryStatus)[keyof typeof RaffleSummaryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleSummaryStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleSummary {
  id: string;
  name: string;
  description: string;
  picture?: string;
  token: RaffleSummaryToken;
  winnersCount: number;
  giftCount: number;
  tags?: string[];
  deadline: number;
  amount: RaffleSummaryAmount;
  ticketPrice: number;
  status: RaffleSummaryStatus;
}

export type RaffleDetailResponseToken = {
  id: string;
  name: string;
  decimals: number;
  verified: boolean;
};

export type RaffleDetailResponseAmount = {
  goal: number;
  raised: number;
};

export type RaffleDetailResponseAddresses = {
  project: string;
  implementer: string;
  service: string;
};

export type RaffleDetailResponseShare = {
  winner: number;
  implementer: number;
  service: number;
};

export type RaffleDetailResponseStatus =
  (typeof RaffleDetailResponseStatus)[keyof typeof RaffleDetailResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleDetailResponseStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleDetailResponse {
  id: string;
  name: string;
  description: string;
  token: RaffleDetailResponseToken;
  tags?: string[];
  pictures: string[];
  giftCount: number;
  winnersCount: number;
  ticketPrice: number;
  deadline: number;
  amount: RaffleDetailResponseAmount;
  addresses: RaffleDetailResponseAddresses;
  share: RaffleDetailResponseShare;
  baker: number;
  status: RaffleDetailResponseStatus;
}

export interface RafflePrize {
  prizeId: string;
  name: string;
  image?: string;
  amount?: number;
}

export interface WinnerBasketListResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: WinnerBasket[];
}

export type WinnerBasketType = (typeof WinnerBasketType)[keyof typeof WinnerBasketType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WinnerBasketType = {
  empty: 'empty',
  shared: 'shared'
} as const;

export interface WinnerBasket {
  basketId: string;
  type: WinnerBasketType;
  /** Calculated share amount */
  shareAmount?: number;
  /** Calculated share percent */
  sharePercent?: number;
  gifts: BasketGiftSimple[];
}

export interface BasketGift {
  /** Gift Id */
  id: string;
  /** Basket Id */
  basketId: string;
  assets: GiftAsset[];
}

export interface GiftAsset {
  /** Token Id */
  tokenId: string;
  /** Token Name */
  tokenName?: string;
  /** Amount */
  amount: number;
}

export interface BasketGiftSimple {
  asset: string;
  amount: number;
  verified: boolean;
}

export type WinnerBasketDetailResponseType =
  (typeof WinnerBasketDetailResponseType)[keyof typeof WinnerBasketDetailResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WinnerBasketDetailResponseType = {
  empty: 'empty',
  shared: 'shared'
} as const;

export interface WinnerBasketDetailResponse {
  basketId: string;
  type: WinnerBasketDetailResponseType;
  tokenId: string;
  tokenName: string;
  sharePercent?: number;
  shareAmount?: number;
  gifts: BasketGiftDetail[];
  transactions: BasketTransaction[];
}

export interface BasketGiftDetail {
  id: string;
  basketId?: string;
  assets: GiftAsset[];
  verified: boolean;
}

export type BasketTransactionType =
  (typeof BasketTransactionType)[keyof typeof BasketTransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketTransactionType = {
  asset_unwrap: 'asset_unwrap',
  ticket_won: 'ticket_won',
  asset_added: 'asset_added'
} as const;

export interface BasketTransaction {
  id: string;
  type: BasketTransactionType;
  amount: number;
  wallet: string;
  address: string;
  createdAt: string;
}

export interface RaffleActivityResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: RaffleActivity[];
}

export type RaffleActivityType = (typeof RaffleActivityType)[keyof typeof RaffleActivityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleActivityType = {
  raffle_created: 'raffle_created',
  ticket_bought: 'ticket_bought',
  upvoted: 'upvoted',
  downvoted: 'downvoted',
  basket_won: 'basket_won',
  gift_added: 'gift_added',
  raising_money: 'raising_money'
} as const;

export type RaffleActivityStatus = (typeof RaffleActivityStatus)[keyof typeof RaffleActivityStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleActivityStatus = {
  successful: 'successful',
  pending: 'pending',
  canceled: 'canceled'
} as const;

export interface RaffleActivity {
  id: string;
  type: RaffleActivityType;
  status?: RaffleActivityStatus;
  address: string;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  basketNumber?: string | null;
  basketType?: string;
  /** @nullable */
  raffleName?: string | null;
  raffleId?: string;
  createdAt: number;
}

export type GetRaffleParams = {
  offset?: number;
  limit?: number;
  status?: GetRaffleStatusItem[];
  tokenIds?: string[];
  tags?: string[];
  ids?: string[];
  text?: string;
  direction?: GetRaffleDirection;
  order?: GetRaffleOrder;
};

export type GetRaffleStatusItem = (typeof GetRaffleStatusItem)[keyof typeof GetRaffleStatusItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleStatusItem = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export type GetRaffleDirection = (typeof GetRaffleDirection)[keyof typeof GetRaffleDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleDirection = {
  ASC: 'ASC',
  DESC: 'DESC'
} as const;

export type GetRaffleOrder = (typeof GetRaffleOrder)[keyof typeof GetRaffleOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleOrder = {
  height: 'height',
  deadline: 'deadline'
} as const;

export type GetRafflesRaffleIdWinnerBasketsParams = {
  offset?: number;
  limit?: number;
  /**
   * Basket filter type
   */
  type?: GetRafflesRaffleIdWinnerBasketsType;
};

export type GetRafflesRaffleIdWinnerBasketsType =
  (typeof GetRafflesRaffleIdWinnerBasketsType)[keyof typeof GetRafflesRaffleIdWinnerBasketsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesRaffleIdWinnerBasketsType = {
  share: 'share',
  empty: 'empty',
  gift: 'gift',
  share_gift: 'share_gift'
} as const;

export type GetActivitiesParams = {
  raffleId?: string;
  offset?: number;
  limit?: number;
  /**
   * Filter activity types
   */
  type?: GetActivitiesType;
  /**
   * Return only activities of the caller
   */
  address?: string;
};

export type GetActivitiesType = (typeof GetActivitiesType)[keyof typeof GetActivitiesType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivitiesType = {
  raffle_created: 'raffle_created',
  ticket_bought: 'ticket_bought',
  voted: 'voted',
  gift_added: 'gift_added'
} as const;

/**
 * @summary Get startup configuration
 */
export const getStartup = () => httpClient<StartupResponse>({ url: `/startup`, method: 'GET' });

/**
 * @summary Get service information
 */
export const getInfoBlockchain = () =>
  httpClient<InfoBlockchainResponse>({ url: `/info/blockchain`, method: 'GET' });

/**
 * @summary Get raffle summaries
 */
export const getRaffle = (params?: GetRaffleParams) =>
  httpClient<RaffleSummaryResponse>({ url: `/raffle`, method: 'GET', params });

/**
 * @summary Get raffle details by ID
 */
export const getRaffleRaffleId = (raffleId: string) =>
  httpClient<RaffleDetailResponse>({ url: `/raffle/${raffleId}`, method: 'GET' });

/**
 * @summary Get winner baskets of a raffle
 */
export const getRafflesRaffleIdWinnerBaskets = (
  raffleId: string,
  params?: GetRafflesRaffleIdWinnerBasketsParams
) =>
  httpClient<WinnerBasketListResponse>({
    url: `/raffles/${raffleId}/winner-baskets`,
    method: 'GET',
    params
  });

/**
 * @summary Get activities
 */
export const getActivities = (params?: GetActivitiesParams) =>
  httpClient<RaffleActivityResponse>({ url: `/activities`, method: 'GET', params });

/**
 * @summary Get details of a winner basket
 */
export const getRafflesRaffleIdWinnerBasketsBasketId = (raffleId: string, basketId: string) =>
  httpClient<WinnerBasketDetailResponse>({
    url: `/raffles/${raffleId}/winner-baskets/${basketId}`,
    method: 'GET'
  });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetStartupResult = NonNullable<Awaited<ReturnType<typeof getStartup>>>;
export type GetInfoBlockchainResult = NonNullable<Awaited<ReturnType<typeof getInfoBlockchain>>>;
export type GetRaffleResult = NonNullable<Awaited<ReturnType<typeof getRaffle>>>;
export type GetRaffleRaffleIdResult = NonNullable<Awaited<ReturnType<typeof getRaffleRaffleId>>>;
export type GetRafflesRaffleIdWinnerBasketsResult = NonNullable<
  Awaited<ReturnType<typeof getRafflesRaffleIdWinnerBaskets>>
>;
export type GetActivitiesResult = NonNullable<Awaited<ReturnType<typeof getActivities>>>;
export type GetRafflesRaffleIdWinnerBasketsBasketIdResult = NonNullable<
  Awaited<ReturnType<typeof getRafflesRaffleIdWinnerBasketsBasketId>>
>;
