/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Raffle Service API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { delay, HttpResponse, http } from 'msw';

import { httpClient } from './http';
export interface StartupResponse {
  txFee: number;
  version: string;
  verifiedTokens: VerifiedToken[];
}

export interface VerifiedToken {
  tokenId: string;
  name: string;
}

export interface InfoResponse {
  lastBlockHeight: number;
  health: string;
  /** Percentage * 10 (e.g. 30 = 3%) */
  serviceFee: number;
  /** Percentage * 10 (e.g. 20 = 2%) */
  implementerFee: number;
  creationFee: number;
}

export interface RaffleSummaryResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: RaffleSummary[];
}

export type RaffleSummaryStatus = (typeof RaffleSummaryStatus)[keyof typeof RaffleSummaryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleSummaryStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleSummary {
  raffleId: string;
  name: string;
  description?: string;
  image?: string;
  collectingTokenId: string;
  /**
   * @minLength 1
   * @maxLength 5
   */
  collectingTokenName?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  winnersCount: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  giftCount: number;
  tags?: string[];
  /** Unix timestamp (seconds) */
  deadline: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  goal: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  ticketPrice: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  soldTicketCount: number;
  status: RaffleSummaryStatus;
}

export type GetRafflesParams = {
  offset?: number;
  limit?: number;
  status?: GetRafflesStatusItem[];
  token?: string[];
  category?: string[];
  name?: string;
  /**
   * Sort order, ascending or descending
   */
  sort?: GetRafflesSort;
  /**
   * Field to sort by
   */
  sortBy?: GetRafflesSortBy;
};

export type GetRafflesStatusItem = (typeof GetRafflesStatusItem)[keyof typeof GetRafflesStatusItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesStatusItem = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export type GetRafflesSort = (typeof GetRafflesSort)[keyof typeof GetRafflesSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesSort = {
  asc: 'asc',
  desc: 'desc'
} as const;

export type GetRafflesSortBy = (typeof GetRafflesSortBy)[keyof typeof GetRafflesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesSortBy = {
  Creation: 'Creation',
  Deadline: 'Deadline'
} as const;

/**
 * @summary Get startup configuration
 */
export const getStartup = () => httpClient<StartupResponse>({ url: `/startup`, method: 'GET' });

/**
 * @summary Get service information
 */
export const getInfo = () => httpClient<InfoResponse>({ url: `/info`, method: 'GET' });

/**
 * @summary Get raffle summaries
 */
export const getRaffles = (params?: GetRafflesParams) =>
  httpClient<RaffleSummaryResponse>({ url: `/raffles`, method: 'GET', params });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetStartupResult = NonNullable<Awaited<ReturnType<typeof getStartup>>>;
export type GetInfoResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>;
export type GetRafflesResult = NonNullable<Awaited<ReturnType<typeof getRaffles>>>;

export const getGetStartupResponseMock = (
  overrideResponse: Partial<StartupResponse> = {}
): StartupResponse => ({
  txFee: faker.number.int({ min: undefined, max: undefined }),
  version: faker.string.alpha({ length: { min: 10, max: 20 } }),
  verifiedTokens: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => ({
    tokenId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } })
  })),
  ...overrideResponse
});

export const getGetInfoResponseMock = (
  overrideResponse: Partial<InfoResponse> = {}
): InfoResponse => ({
  lastBlockHeight: faker.number.int({ min: undefined, max: undefined }),
  health: faker.string.alpha({ length: { min: 10, max: 20 } }),
  serviceFee: faker.number.int({ min: undefined, max: undefined }),
  implementerFee: faker.number.int({ min: undefined, max: undefined }),
  creationFee: faker.number.int({ min: undefined, max: undefined }),
  ...overrideResponse
});

export const getGetRafflesResponseMock = (
  overrideResponse: Partial<RaffleSummaryResponse> = {}
): RaffleSummaryResponse => ({
  total: faker.number.int({ min: 1, max: 1000 }),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    raffleId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined
    ]),
    image: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    collectingTokenId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    collectingTokenName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 1, max: 5 } }),
      undefined
    ]),
    winnersCount: faker.number.int({ min: 1, max: 5 }),
    giftCount: faker.number.int({ min: 1, max: 5 }),
    tags: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha({ length: { min: 10, max: 20 } })
      ),
      undefined
    ]),
    deadline: faker.number.int({ min: undefined, max: undefined }),
    goal: faker.number.int({ min: 1, max: 100 }),
    ticketPrice: faker.number.int({ min: 1, max: 100 }),
    soldTicketCount: faker.number.int({ min: 1, max: 100 }),
    status: faker.helpers.arrayElement(['active', 'successful', 'failed'] as const)
  })),
  ...overrideResponse
});

export const getGetStartupMockHandler = (
  overrideResponse?:
    | StartupResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<StartupResponse> | StartupResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/startup',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetStartupResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetInfoMockHandler = (
  overrideResponse?:
    | InfoResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<InfoResponse> | InfoResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/info',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetInfoResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetRafflesMockHandler = (
  overrideResponse?:
    | RaffleSummaryResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<RaffleSummaryResponse> | RaffleSummaryResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/raffles',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRafflesResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
export const getRaffleServiceAPIMock = () => [
  getGetStartupMockHandler(),
  getGetInfoMockHandler(),
  getGetRafflesMockHandler()
];
