/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Raffle Service API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { delay, HttpResponse, http } from 'msw';

import { httpClient } from './http';
export interface StartupResponse {
  txFee: number;
  version: string;
  verifiedTokens: VerifiedToken[];
}

export interface VerifiedToken {
  tokenId: string;
  name: string;
}

export interface InfoResponse {
  lastBlockHeight: number;
  health: string;
  /** Percentage * 10 (e.g. 30 = 3%) */
  serviceFee: number;
  /** Percentage * 10 (e.g. 20 = 2%) */
  implementerFee: number;
  creationFee: number;
}

export interface RaffleSummaryResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: RaffleSummary[];
}

export type RaffleSummaryStatus = (typeof RaffleSummaryStatus)[keyof typeof RaffleSummaryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleSummaryStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleSummary {
  raffleId: string;
  name: string;
  description?: string;
  image?: string;
  collectingTokenId: string;
  /**
   * @minLength 1
   * @maxLength 5
   */
  collectingTokenName?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  winnersCount: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  giftCount: number;
  tags?: string[];
  /** Unix timestamp (seconds) */
  deadline: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  goal: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  ticketPrice: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  soldTicketCount: number;
  status: RaffleSummaryStatus;
}

export type RaffleDetailResponseStatus =
  (typeof RaffleDetailResponseStatus)[keyof typeof RaffleDetailResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleDetailResponseStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleDetailResponse {
  raffleId: string;
  name: string;
  description?: string;
  image?: string;
  collectingTokenId: string;
  /**
   * @minLength 1
   * @maxLength 5
   */
  collectingTokenName?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  winnersCount: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  giftCount: number;
  tags?: string[];
  /** Unix timestamp (seconds) */
  deadline: number;
  /** @maximum 100 */
  goal: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  ticketPrice: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  soldTicketCount: number;
  status: RaffleDetailResponseStatus;
  /** Unix timestamp (seconds) */
  createdAt?: number;
  creator?: string;
  prizes?: RafflePrize[];
}

export interface RafflePrize {
  prizeId: string;
  name: string;
  image?: string;
  amount?: number;
}

export type VoteRequestVote = (typeof VoteRequestVote)[keyof typeof VoteRequestVote];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteRequestVote = {
  up: 'up',
  down: 'down'
} as const;

export interface VoteRequest {
  vote: VoteRequestVote;
}

export interface VoteResponse {
  raffleId: string;
  /** @minimum 0 */
  upVotes: number;
  /** @minimum 0 */
  downVotes: number;
}

export interface PinRequest {
  pinned: boolean;
}

export interface PinResponse {
  raffleId: string;
  pinned: boolean;
}

export interface WinnerBasketListResponse {
  total: number;
  items: WinnerBasket[];
}

export interface WinnerBasket {
  basketId: string;
  /** Basket index shown in UI */
  share?: number;
  /**
   * Calculated share amount
   * @minimum 1
   * @maximum 1000
   */
  shareAmount?: number;
  /**
   * Calculated share amount percent
   * @minimum 0
   * @maximum 100
   */
  sharePercent?: number;
  gifts?: BasketGift[];
  /** Token ID */
  tokenId?: string;
  /** Token Name */
  tokenName?: string;
}

export interface BasketGift {
  name: string;
  amount?: number;
}

export interface RaffleActivityResponse {
  /**
   * @minimum 0
   * @maximum 10000
   */
  total: number;
  items: RaffleActivity[];
}

export interface RaffleActivity {
  activityId: string;
  type: RaffleActivityType;
  /** Wallet address */
  wallet: string;
  /**
   * Ticket count or vote weight
   * @nullable
   */
  amount?: number | null;
  /** Human readable text */
  description?: string;
  /** Unix timestamp (seconds) */
  createdAt: number;
}

export type RaffleActivityType = (typeof RaffleActivityType)[keyof typeof RaffleActivityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleActivityType = {
  raffle_created: 'raffle_created',
  ticket_bought: 'ticket_bought',
  upvoted: 'upvoted',
  downvoted: 'downvoted',
  gift_added: 'gift_added'
} as const;

export type GetRafflesParams = {
  offset?: number;
  limit?: number;
  status?: GetRafflesStatusItem[];
  token?: string[];
  category?: string[];
  name?: string;
  /**
   * Sort order, ascending or descending
   */
  sort?: GetRafflesSort;
  /**
   * Field to sort by
   */
  sortBy?: GetRafflesSortBy;
};

export type GetRafflesStatusItem = (typeof GetRafflesStatusItem)[keyof typeof GetRafflesStatusItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesStatusItem = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export type GetRafflesSort = (typeof GetRafflesSort)[keyof typeof GetRafflesSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesSort = {
  asc: 'asc',
  desc: 'desc'
} as const;

export type GetRafflesSortBy = (typeof GetRafflesSortBy)[keyof typeof GetRafflesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesSortBy = {
  Creation: 'Creation',
  Deadline: 'Deadline'
} as const;

export type GetRafflesRaffleIdWinnerBasketsParams = {
  offset?: number;
  limit?: number;
  /**
   * Basket filter type
   */
  type?: GetRafflesRaffleIdWinnerBasketsType;
};

export type GetRafflesRaffleIdWinnerBasketsType =
  (typeof GetRafflesRaffleIdWinnerBasketsType)[keyof typeof GetRafflesRaffleIdWinnerBasketsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesRaffleIdWinnerBasketsType = {
  share: 'share',
  empty: 'empty',
  gift: 'gift',
  share_gift: 'share_gift'
} as const;

export type GetRafflesRaffleIdActivitiesParams = {
  offset?: number;
  limit?: number;
  /**
   * Filter activity types
   */
  type?: GetRafflesRaffleIdActivitiesType;
  /**
   * Return only activities of the caller
   */
  onlyMyAddress?: boolean;
};

export type GetRafflesRaffleIdActivitiesType =
  (typeof GetRafflesRaffleIdActivitiesType)[keyof typeof GetRafflesRaffleIdActivitiesType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesRaffleIdActivitiesType = {
  raffle_created: 'raffle_created',
  ticket_bought: 'ticket_bought',
  upvoted: 'upvoted',
  downvoted: 'downvoted',
  gift_added: 'gift_added'
} as const;

/**
 * @summary Get startup configuration
 */
export const getStartup = () => httpClient<StartupResponse>({ url: `/startup`, method: 'GET' });

/**
 * @summary Get service information
 */
export const getInfo = () => httpClient<InfoResponse>({ url: `/info`, method: 'GET' });

/**
 * @summary Get raffle summaries
 */
export const getRaffles = (params?: GetRafflesParams) =>
  httpClient<RaffleSummaryResponse>({ url: `/raffles`, method: 'GET', params });

/**
 * @summary Get raffle details by ID
 */
export const getRafflesRaffleId = (raffleId: string) =>
  httpClient<RaffleDetailResponse>({ url: `/raffles/${raffleId}`, method: 'GET' });

/**
 * @summary Vote up or down a raffle
 */
export const postRafflesRaffleIdVote = (raffleId: string, voteRequest: VoteRequest) =>
  httpClient<VoteResponse>({
    url: `/raffles/${raffleId}/vote`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: voteRequest
  });

/**
 * @summary Pin or unpin a raffle
 */
export const postRafflesRaffleIdPin = (raffleId: string, pinRequest: PinRequest) =>
  httpClient<PinResponse>({
    url: `/raffles/${raffleId}/pin`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: pinRequest
  });

/**
 * @summary Get winner baskets of a raffle
 */
export const getRafflesRaffleIdWinnerBaskets = (
  raffleId: string,
  params?: GetRafflesRaffleIdWinnerBasketsParams
) =>
  httpClient<WinnerBasketListResponse>({
    url: `/raffles/${raffleId}/winner-baskets`,
    method: 'GET',
    params
  });

/**
 * @summary Get raffle activities
 */
export const getRafflesRaffleIdActivities = (
  raffleId: string,
  params?: GetRafflesRaffleIdActivitiesParams
) =>
  httpClient<RaffleActivityResponse>({
    url: `/raffles/${raffleId}/activities`,
    method: 'GET',
    params
  });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetStartupResult = NonNullable<Awaited<ReturnType<typeof getStartup>>>;
export type GetInfoResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>;
export type GetRafflesResult = NonNullable<Awaited<ReturnType<typeof getRaffles>>>;
export type GetRafflesRaffleIdResult = NonNullable<Awaited<ReturnType<typeof getRafflesRaffleId>>>;
export type PostRafflesRaffleIdVoteResult = NonNullable<
  Awaited<ReturnType<typeof postRafflesRaffleIdVote>>
>;
export type PostRafflesRaffleIdPinResult = NonNullable<
  Awaited<ReturnType<typeof postRafflesRaffleIdPin>>
>;
export type GetRafflesRaffleIdWinnerBasketsResult = NonNullable<
  Awaited<ReturnType<typeof getRafflesRaffleIdWinnerBaskets>>
>;
export type GetRafflesRaffleIdActivitiesResult = NonNullable<
  Awaited<ReturnType<typeof getRafflesRaffleIdActivities>>
>;

export const getGetStartupResponseMock = (
  overrideResponse: Partial<StartupResponse> = {}
): StartupResponse => ({
  txFee: faker.number.int({ min: undefined, max: undefined }),
  version: faker.string.alpha({ length: { min: 10, max: 20 } }),
  verifiedTokens: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => ({
    tokenId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } })
  })),
  ...overrideResponse
});

export const getGetInfoResponseMock = (
  overrideResponse: Partial<InfoResponse> = {}
): InfoResponse => ({
  lastBlockHeight: faker.number.int({ min: undefined, max: undefined }),
  health: faker.string.alpha({ length: { min: 10, max: 20 } }),
  serviceFee: faker.number.int({ min: undefined, max: undefined }),
  implementerFee: faker.number.int({ min: undefined, max: undefined }),
  creationFee: faker.number.int({ min: undefined, max: undefined }),
  ...overrideResponse
});

export const getGetRafflesResponseMock = (
  overrideResponse: Partial<RaffleSummaryResponse> = {}
): RaffleSummaryResponse => ({
  total: faker.number.int({ min: 1, max: 1000 }),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    raffleId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined
    ]),
    image: faker.helpers.arrayElement([faker.internet.url(), undefined]),
    collectingTokenId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    collectingTokenName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 1, max: 5 } }),
      undefined
    ]),
    winnersCount: faker.number.int({ min: 1, max: 5 }),
    giftCount: faker.number.int({ min: 1, max: 5 }),
    tags: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
        faker.string.alpha({ length: { min: 10, max: 20 } })
      ),
      undefined
    ]),
    deadline: faker.number.int({ min: undefined, max: undefined }),
    goal: faker.number.int({ min: 1, max: 100 }),
    ticketPrice: faker.number.int({ min: 1, max: 100 }),
    soldTicketCount: faker.number.int({ min: 1, max: 100 }),
    status: faker.helpers.arrayElement(['active', 'successful', 'failed'] as const)
  })),
  ...overrideResponse
});

export const getGetRafflesRaffleIdResponseMock = (
  overrideResponse: Partial<RaffleDetailResponse> = {}
): RaffleDetailResponse => ({
  raffleId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined
  ]),
  image: faker.helpers.arrayElement([faker.internet.url(), undefined]),
  collectingTokenId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  collectingTokenName: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 1, max: 5 } }),
    undefined
  ]),
  winnersCount: faker.number.int({ min: 1, max: 5 }),
  giftCount: faker.number.int({ min: 1, max: 5 }),
  tags: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
      faker.string.alpha({ length: { min: 10, max: 20 } })
    ),
    undefined
  ]),
  deadline: faker.number.int({ min: undefined, max: undefined }),
  goal: faker.number.int({ min: undefined, max: 100 }),
  ticketPrice: faker.number.int({ min: 1, max: 100 }),
  soldTicketCount: faker.number.int({ min: 1, max: 100 }),
  status: faker.helpers.arrayElement(['active', 'successful', 'failed'] as const),
  createdAt: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined
  ]),
  creator: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined
  ]),
  prizes: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      prizeId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      image: faker.helpers.arrayElement([faker.internet.url(), undefined]),
      amount: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined
      ])
    })),
    undefined
  ]),
  ...overrideResponse
});

export const getPostRafflesRaffleIdVoteResponseMock = (
  overrideResponse: Partial<VoteResponse> = {}
): VoteResponse => ({
  raffleId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  upVotes: faker.number.int({ min: 0, max: undefined }),
  downVotes: faker.number.int({ min: 0, max: undefined }),
  ...overrideResponse
});

export const getPostRafflesRaffleIdPinResponseMock = (
  overrideResponse: Partial<PinResponse> = {}
): PinResponse => ({
  raffleId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  pinned: faker.datatype.boolean(),
  ...overrideResponse
});

export const getGetRafflesRaffleIdWinnerBasketsResponseMock = (
  overrideResponse: Partial<WinnerBasketListResponse> = {}
): WinnerBasketListResponse => ({
  total: faker.number.int({ min: undefined, max: undefined }),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    basketId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    share: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined
    ]),
    shareAmount: faker.helpers.arrayElement([faker.number.int({ min: 1, max: 1000 }), undefined]),
    sharePercent: faker.helpers.arrayElement([faker.number.int({ min: 0, max: 100 }), undefined]),
    gifts: faker.helpers.arrayElement([
      Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        amount: faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          undefined
        ])
      })),
      undefined
    ]),
    tokenId: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined
    ]),
    tokenName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined
    ])
  })),
  ...overrideResponse
});

export const getGetRafflesRaffleIdActivitiesResponseMock = (
  overrideResponse: Partial<RaffleActivityResponse> = {}
): RaffleActivityResponse => ({
  total: faker.number.int({ min: 0, max: 10000 }),
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    activityId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.helpers.arrayElement(Object.values(RaffleActivityType)),
    wallet: faker.string.alpha({ length: { min: 10, max: 20 } }),
    amount: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), null]),
      undefined
    ]),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined
    ]),
    createdAt: faker.number.int({ min: undefined, max: undefined })
  })),
  ...overrideResponse
});

export const getGetStartupMockHandler = (
  overrideResponse?:
    | StartupResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<StartupResponse> | StartupResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/startup',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetStartupResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetInfoMockHandler = (
  overrideResponse?:
    | InfoResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<InfoResponse> | InfoResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/info',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetInfoResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetRafflesMockHandler = (
  overrideResponse?:
    | RaffleSummaryResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<RaffleSummaryResponse> | RaffleSummaryResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/raffles',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRafflesResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetRafflesRaffleIdMockHandler = (
  overrideResponse?:
    | RaffleDetailResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<RaffleDetailResponse> | RaffleDetailResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/raffles/:raffleId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRafflesRaffleIdResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getPostRafflesRaffleIdVoteMockHandler = (
  overrideResponse?:
    | VoteResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0]
      ) => Promise<VoteResponse> | VoteResponse),
  options?: RequestHandlerOptions
) =>
  http.post(
    '*/raffles/:raffleId/vote',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostRafflesRaffleIdVoteResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getPostRafflesRaffleIdPinMockHandler = (
  overrideResponse?:
    | PinResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0]
      ) => Promise<PinResponse> | PinResponse),
  options?: RequestHandlerOptions
) =>
  http.post(
    '*/raffles/:raffleId/pin',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPostRafflesRaffleIdPinResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetRafflesRaffleIdWinnerBasketsMockHandler = (
  overrideResponse?:
    | WinnerBasketListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<WinnerBasketListResponse> | WinnerBasketListResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/raffles/:raffleId/winner-baskets',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRafflesRaffleIdWinnerBasketsResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );

export const getGetRafflesRaffleIdActivitiesMockHandler = (
  overrideResponse?:
    | RaffleActivityResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<RaffleActivityResponse> | RaffleActivityResponse),
  options?: RequestHandlerOptions
) =>
  http.get(
    '*/raffles/:raffleId/activities',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRafflesRaffleIdActivitiesResponseMock()
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    },
    options
  );
export const getRaffleServiceAPIMock = () => [
  getGetStartupMockHandler(),
  getGetInfoMockHandler(),
  getGetRafflesMockHandler(),
  getGetRafflesRaffleIdMockHandler(),
  getPostRafflesRaffleIdVoteMockHandler(),
  getPostRafflesRaffleIdPinMockHandler(),
  getGetRafflesRaffleIdWinnerBasketsMockHandler(),
  getGetRafflesRaffleIdActivitiesMockHandler()
];
