/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rafflora API
 * API for Rafflora operations
 * OpenAPI spec version: 0.0.0
 */
import { httpClient } from './httpBitcoin';
export type PostApiDonationBody = {
  /**
   * Number of tickets to buy
   */
  ticketCount: number;
  /**
   * Raffle Id to donate to
   * @minLength 1
   */
  raffleId: string;
  /**
   * Donator address
   * @minLength 1
   */
  donatorAddress: string;
  /**
   * Captcha token when captcha validation is enabled
   * @minLength 1
   */
  captchaToken?: string;
};

export type PostApiDonation200Data = {
  bitcoinAddress?: string;
  satoshiAmount?: string;
  tokenId?: string;
  tokenAmount?: string;
};

export type PostApiDonation200 = {
  success: boolean;
  message: string;
  data: PostApiDonation200Data;
};

export type GetTokensBridgeableParams = {
  /**
   * Token ID to check to be bridgeable
   */
  tokenId: string;
};

export type GetTokensBridgeable200 = {
  /** Requested token ID */
  tokenId: string;
  /** Whether the token is bridgeable or not */
  bridgeable: boolean;
};

export type GetInfo200 = {
  /** Captcha site key for frontend */
  siteKey: string;
  /** btc-payment service version */
  version: string;
};

/**
 * Calculate required resources for buying raffle tickets
 */
export const postApiDonation = (postApiDonationBody: PostApiDonationBody) =>
  httpClient<PostApiDonation200>({
    url: `/api/donation`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postApiDonationBody
  });

/**
 * Checks if a token is bridgeable
 */
export const getTokensBridgeable = (params: GetTokensBridgeableParams) =>
  httpClient<GetTokensBridgeable200>({ url: `/tokens/bridgeable`, method: 'GET', params });

/**
 * Returns captcha site key for frontend
 */
export const getInfo = () => httpClient<GetInfo200>({ url: `/info`, method: 'GET' });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostApiDonationResult = NonNullable<Awaited<ReturnType<typeof postApiDonation>>>;
export type GetTokensBridgeableResult = NonNullable<
  Awaited<ReturnType<typeof getTokensBridgeable>>
>;
export type GetInfoResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>;
