/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Raffle Service API
 * OpenAPI spec version: 1.0.0
 */
import { httpClient } from './httpMain';
export interface StartupResponse {
  txFee: number;
  version: string;
  verifiedTokens: VerifiedToken[];
}

export interface VerifiedToken {
  tokenId: string;
  name: string;
}

export type InfoBlockchainResponseFee = {
  tx: number;
  service: number;
  implementer: number;
  creation: number;
};

export interface InfoBlockchainResponse {
  fee: InfoBlockchainResponseFee;
  height: number;
}

export interface RaffleSummaryResponse {
  /**
   * @minimum 1
   * @maximum 1000
   */
  total: number;
  items: RaffleSummary[];
}

export type RaffleSummaryToken = {
  id: string;
  name: string;
  decimals: number;
  isVerified: boolean;
};

export type RaffleSummaryAmount = {
  goal: number;
  raised: number;
};

export type RaffleSummaryStatus = (typeof RaffleSummaryStatus)[keyof typeof RaffleSummaryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleSummaryStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleSummary {
  id: string;
  name: string;
  description: string;
  picture?: string;
  token: RaffleSummaryToken;
  winnersCount: number;
  giftCount: number;
  tags?: string[];
  deadline: number;
  amount: RaffleSummaryAmount;
  ticketPrice: number;
  status: RaffleSummaryStatus;
}

export type RaffleDetailResponseToken = {
  id: string;
  name: string;
  decimals: number;
  isVerified: boolean;
};

export type RaffleDetailResponseAmount = {
  goal: number;
  raised: number;
};

export type RaffleDetailResponseAddresses = {
  project: string;
  implementer: string;
  service: string;
};

export type RaffleDetailResponseShare = {
  winner: number;
  implementer: number;
  service: number;
};

export type RaffleDetailResponseStatus =
  (typeof RaffleDetailResponseStatus)[keyof typeof RaffleDetailResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleDetailResponseStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleDetailResponse {
  id: string;
  name: string;
  description: string;
  token: RaffleDetailResponseToken;
  tags?: string[];
  pictures: string[];
  giftCount: number;
  winnersCount: number;
  ticketPrice: number;
  deadline: number;
  amount: RaffleDetailResponseAmount;
  addresses: RaffleDetailResponseAddresses;
  share: RaffleDetailResponseShare;
  backerCount: number;
  status: RaffleDetailResponseStatus;
}

export interface RafflePrize {
  prizeId: string;
  name: string;
  image?: string;
  amount?: number;
}

export interface WinnerBasketListResponse {
  total: number;
  items: WinnerBasketSummary[];
}

export interface WinnerBasketSummary {
  index: number;
  share: number;
  gifts: BasketGift[];
}

export interface BasketGift {
  tokenId: string;
  amount: number;
}

export interface TokensResponse {
  items: TokenSummary[];
}

export interface TokenSummary {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
}

export type WinnerBasketDetailResponseType =
  (typeof WinnerBasketDetailResponseType)[keyof typeof WinnerBasketDetailResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WinnerBasketDetailResponseType = {
  empty: 'empty',
  shared: 'shared'
} as const;

export interface WinnerBasketDetailResponse {
  index?: number;
  type: WinnerBasketDetailResponseType;
  tokenId: string;
  tokenName: string;
  sharePercent?: number;
  shareAmount?: number;
  gifts: BasketGift[];
  transactions: BasketTransaction[];
}

export type BasketTransactionType =
  (typeof BasketTransactionType)[keyof typeof BasketTransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketTransactionType = {
  asset_unwrap: 'asset_unwrap',
  ticket_won: 'ticket_won',
  asset_added: 'asset_added'
} as const;

export interface BasketTransaction {
  id: string;
  type: BasketTransactionType;
  amount: number;
  wallet: string;
  address: string;
  createdAt: string;
}

export type GetRaffleParams = {
  offset?: number;
  limit?: number;
  status?: GetRaffleStatusItem[];
  tokenIds?: string[];
  tags?: string[];
  ids?: string[];
  text?: string;
  direction?: GetRaffleDirection;
  order?: GetRaffleOrder;
};

export type GetRaffleStatusItem = (typeof GetRaffleStatusItem)[keyof typeof GetRaffleStatusItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleStatusItem = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export type GetRaffleDirection = (typeof GetRaffleDirection)[keyof typeof GetRaffleDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleDirection = {
  ASC: 'ASC',
  DESC: 'DESC'
} as const;

export type GetRaffleOrder = (typeof GetRaffleOrder)[keyof typeof GetRaffleOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleOrder = {
  height: 'height',
  deadline: 'deadline'
} as const;

export type GetRaffleRaffleIdBasketParams = {
  offset?: number;
  limit?: number;
  share?: GetRaffleRaffleIdBasketShare;
  gift?: GetRaffleRaffleIdBasketGift;
  index?: number;
};

export type GetRaffleRaffleIdBasketShare =
  (typeof GetRaffleRaffleIdBasketShare)[keyof typeof GetRaffleRaffleIdBasketShare];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketShare = {
  'non-empty': 'non-empty',
  empty: 'empty'
} as const;

export type GetRaffleRaffleIdBasketGift =
  (typeof GetRaffleRaffleIdBasketGift)[keyof typeof GetRaffleRaffleIdBasketGift];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketGift = {
  'non-empty': 'non-empty',
  empty: 'empty'
} as const;

export type GetActivityParams = {
  address?: string;
  raffleId?: string;
  types?:
    | GetActivityTypesAnyOfItem[]
    | 'creation'
    | 'donation'
    | 'gift'
    | 'ticket_redeem'
    | 'gift_return';
  offset?: number;
  limit?: number;
};

export type GetActivityTypesAnyOfItem =
  (typeof GetActivityTypesAnyOfItem)[keyof typeof GetActivityTypesAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivityTypesAnyOfItem = {
  creation: 'creation',
  donation: 'donation',
  gift: 'gift',
  ticket_redeem: 'ticket_redeem',
  gift_return: 'gift_return'
} as const;

export type GetActivity200ItemsItemType =
  (typeof GetActivity200ItemsItemType)[keyof typeof GetActivity200ItemsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivity200ItemsItemType = {
  creation: 'creation',
  donation: 'donation',
  gift: 'gift',
  ticket_redeem: 'ticket_redeem',
  gift_return: 'gift_return'
} as const;

export type GetActivity200ItemsItemStatus =
  (typeof GetActivity200ItemsItemStatus)[keyof typeof GetActivity200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivity200ItemsItemStatus = {
  success: 'success',
  failed: 'failed',
  pending: 'pending'
} as const;

export type GetActivity200ItemsItem = {
  address: string;
  raffleId: string;
  type: GetActivity200ItemsItemType;
  ticketCount?: number;
  txId: string;
  raffleName?: string;
  height: number;
  timestamp?: number;
  status: GetActivity200ItemsItemStatus;
};

export type GetActivity200 = {
  items: GetActivity200ItemsItem[];
  total: number;
};

export type GetTokensParams = {
  tokenIds: string[] | string;
};

export type GetTokensSearchParams = {
  /**
   * @minLength 2
   */
  query: string;
  offset?: number;
  /**
   * @maximum 100
   */
  limit?: number;
};

export type GetTokensSearch200ItemsItem = {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
};

export type GetTokensSearch200 = {
  items: GetTokensSearch200ItemsItem[];
  total: number;
};

/**
 * @summary Get startup configuration
 */
export const getStartup = () => httpClient<StartupResponse>({ url: `/startup`, method: 'GET' });

/**
 * @summary Get service information
 */
export const getInfoBlockchain = () =>
  httpClient<InfoBlockchainResponse>({ url: `/info/blockchain`, method: 'GET' });

/**
 * @summary Get raffle summaries
 */
export const getRaffle = (params?: GetRaffleParams) =>
  httpClient<RaffleSummaryResponse>({ url: `/raffle`, method: 'GET', params });

/**
 * @summary Get raffle details by ID
 */
export const getRaffleRaffleId = (raffleId: string) =>
  httpClient<RaffleDetailResponse>({ url: `/raffle/${raffleId}`, method: 'GET' });

/**
 * @summary Get winner baskets of a raffle
 */
export const getRaffleRaffleIdBasket = (raffleId: string, params?: GetRaffleRaffleIdBasketParams) =>
  httpClient<WinnerBasketListResponse>({
    url: `/raffle/${raffleId}/basket`,
    method: 'GET',
    params
  });

/**
 * @summary Get details of a winner basket
 */
export const getRafflesRaffleIdBasketBasketId = (raffleId: string, basketId: number) =>
  httpClient<WinnerBasketDetailResponse>({
    url: `/raffles/${raffleId}/basket/${basketId}`,
    method: 'GET'
  });

/**
 * Returns a paginated list of user activities
 */
export const getActivity = (params?: GetActivityParams) =>
  httpClient<GetActivity200>({ url: `/activity`, method: 'GET', params });

export const getTokens = (params: GetTokensParams) =>
  httpClient<TokensResponse>({ url: `/tokens`, method: 'GET', params });

/**
 * Returns token information for given query
 */
export const getTokensSearch = (params: GetTokensSearchParams) =>
  httpClient<GetTokensSearch200>({ url: `/tokens/search`, method: 'GET', params });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetStartupResult = NonNullable<Awaited<ReturnType<typeof getStartup>>>;
export type GetInfoBlockchainResult = NonNullable<Awaited<ReturnType<typeof getInfoBlockchain>>>;
export type GetRaffleResult = NonNullable<Awaited<ReturnType<typeof getRaffle>>>;
export type GetRaffleRaffleIdResult = NonNullable<Awaited<ReturnType<typeof getRaffleRaffleId>>>;
export type GetRaffleRaffleIdBasketResult = NonNullable<
  Awaited<ReturnType<typeof getRaffleRaffleIdBasket>>
>;
export type GetRafflesRaffleIdBasketBasketIdResult = NonNullable<
  Awaited<ReturnType<typeof getRafflesRaffleIdBasketBasketId>>
>;
export type GetActivityResult = NonNullable<Awaited<ReturnType<typeof getActivity>>>;
export type GetTokensResult = NonNullable<Awaited<ReturnType<typeof getTokens>>>;
export type GetTokensSearchResult = NonNullable<Awaited<ReturnType<typeof getTokensSearch>>>;
