/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rafflora API
 * API for Rafflora operations
 * OpenAPI spec version: 0.0.0
 */
import { httpClient } from './httpMain';
export type GetInfoVersion200 = {
  version: string;
};

export type GetInfoBlockchain200Fee = {
  tx: number;
  service: number;
  implementer: number;
  creation: number;
};

export type GetInfoBlockchain200 = {
  fee: GetInfoBlockchain200Fee;
  height: number;
};

export type GetInfoBlockchain500 = {
  message: string;
};

export type GetInfoTagsParams = {
  query?: string;
};

export type GetRaffleParams = {
  text?: string;
  tokenIds?: string[] | string;
  tags?: string[] | string;
  ids?: string[] | string;
  status?: GetRaffleStatusAnyOfItem[] | 'active' | 'failed' | 'successful';
  order?: GetRaffleOrder;
  direction?: GetRaffleDirection;
  offset?: number;
  /**
   * @maximum 100
   */
  limit?: number;
};

export type GetRaffleStatusAnyOfItem =
  (typeof GetRaffleStatusAnyOfItem)[keyof typeof GetRaffleStatusAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleStatusAnyOfItem = {
  active: 'active',
  failed: 'failed',
  successful: 'successful'
} as const;

export type GetRaffleOrder = (typeof GetRaffleOrder)[keyof typeof GetRaffleOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleOrder = {
  height: 'height',
  deadline: 'deadline'
} as const;

export type GetRaffleDirection = (typeof GetRaffleDirection)[keyof typeof GetRaffleDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleDirection = {
  ASC: 'ASC',
  DESC: 'DESC'
} as const;

export type GetRaffle200ItemsItemToken = {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
};

export type GetRaffle200ItemsItemAmount = {
  goal: number;
  raised: number;
};

export type GetRaffle200ItemsItemStatus =
  (typeof GetRaffle200ItemsItemStatus)[keyof typeof GetRaffle200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffle200ItemsItemStatus = {
  active: 'active',
  failed: 'failed',
  successful: 'successful'
} as const;

export type GetRaffle200ItemsItem = {
  id: string;
  name: string;
  description: string;
  token: GetRaffle200ItemsItemToken;
  winnersCount: number;
  giftCount: number;
  tags?: string[];
  deadline: number;
  amount: GetRaffle200ItemsItemAmount;
  ticketPrice: number;
  status: GetRaffle200ItemsItemStatus;
  picture?: string;
};

export type GetRaffle200 = {
  items: GetRaffle200ItemsItem[];
  total: number;
};

export type GetRaffleRaffleId200Token = {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
};

export type GetRaffleRaffleId200Amount = {
  goal: number;
  raised: number;
};

export type GetRaffleRaffleId200Status =
  (typeof GetRaffleRaffleId200Status)[keyof typeof GetRaffleRaffleId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleId200Status = {
  active: 'active',
  failed: 'failed',
  successful: 'successful'
} as const;

export type GetRaffleRaffleId200Addresses = {
  project: string;
  implementer: string;
  service: string;
};

export type GetRaffleRaffleId200Share = {
  winner: number;
  implementer: number;
  service: number;
};

export type GetRaffleRaffleId200 = {
  id: string;
  name: string;
  description: string;
  token: GetRaffleRaffleId200Token;
  winnersCount: number;
  giftCount: number;
  tags?: string[];
  deadline: number;
  amount: GetRaffleRaffleId200Amount;
  ticketPrice: number;
  status: GetRaffleRaffleId200Status;
  pictures: string[];
  addresses: GetRaffleRaffleId200Addresses;
  share: GetRaffleRaffleId200Share;
  backerCount: number;
};

export type GetRaffleRaffleId404 = {
  message: string;
};

export type GetRaffleRaffleIdBasketParams = {
  offset?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  share?: GetRaffleRaffleIdBasketShare;
  gift?: GetRaffleRaffleIdBasketGift;
  index?: number;
};

export type GetRaffleRaffleIdBasketShare =
  (typeof GetRaffleRaffleIdBasketShare)[keyof typeof GetRaffleRaffleIdBasketShare];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketShare = {
  'non-empty': 'non-empty',
  empty: 'empty'
} as const;

export type GetRaffleRaffleIdBasketGift =
  (typeof GetRaffleRaffleIdBasketGift)[keyof typeof GetRaffleRaffleIdBasketGift];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketGift = {
  'non-empty': 'non-empty',
  empty: 'empty'
} as const;

export type GetRaffleRaffleIdBasket200ItemsItemGiftsItem = {
  tokenId: string;
  amount: number;
};

export type GetRaffleRaffleIdBasket200ItemsItem = {
  index: number;
  share: number;
  gifts: GetRaffleRaffleIdBasket200ItemsItemGiftsItem[];
};

export type GetRaffleRaffleIdBasket200 = {
  items: GetRaffleRaffleIdBasket200ItemsItem[];
  total: number;
};

export type GetRaffleRaffleIdBasketWinnerIndexTransactionsParams = {
  offset?: number;
  limit?: number;
};

export type GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemType =
  (typeof GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemType)[keyof typeof GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemType = {
  creation: 'creation',
  donation: 'donation',
  gift: 'gift',
  ticket_redeem: 'ticket_redeem',
  gift_return: 'gift_return'
} as const;

export type GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemStatus =
  (typeof GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemStatus)[keyof typeof GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemStatus = {
  success: 'success',
  failed: 'failed',
  pending: 'pending'
} as const;

export type GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItem = {
  address: string;
  raffleId: string;
  type: GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemType;
  ticketCount?: number;
  winnerIndex?: number;
  txId: string;
  raffleName?: string;
  height: number;
  timestamp?: number;
  status: GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItemStatus;
};

export type GetRaffleRaffleIdBasketWinnerIndexTransactions200 = {
  items: GetRaffleRaffleIdBasketWinnerIndexTransactions200ItemsItem[];
  total: number;
};

export type GetActivityParams = {
  address?: string;
  raffleId?: string;
  types?:
    | GetActivityTypesAnyOfItem[]
    | 'creation'
    | 'donation'
    | 'gift'
    | 'ticket_redeem'
    | 'gift_return';
  offset?: number;
  limit?: number;
};

export type GetActivityTypesAnyOfItem =
  (typeof GetActivityTypesAnyOfItem)[keyof typeof GetActivityTypesAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivityTypesAnyOfItem = {
  creation: 'creation',
  donation: 'donation',
  gift: 'gift',
  ticket_redeem: 'ticket_redeem',
  gift_return: 'gift_return'
} as const;

export type GetActivity200ItemsItemType =
  (typeof GetActivity200ItemsItemType)[keyof typeof GetActivity200ItemsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivity200ItemsItemType = {
  creation: 'creation',
  donation: 'donation',
  gift: 'gift',
  ticket_redeem: 'ticket_redeem',
  gift_return: 'gift_return'
} as const;

export type GetActivity200ItemsItemStatus =
  (typeof GetActivity200ItemsItemStatus)[keyof typeof GetActivity200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivity200ItemsItemStatus = {
  success: 'success',
  failed: 'failed',
  pending: 'pending'
} as const;

export type GetActivity200ItemsItem = {
  address: string;
  raffleId: string;
  type: GetActivity200ItemsItemType;
  ticketCount?: number;
  winnerIndex?: number;
  txId: string;
  raffleName?: string;
  height: number;
  timestamp?: number;
  status: GetActivity200ItemsItemStatus;
};

export type GetActivity200 = {
  items: GetActivity200ItemsItem[];
  total: number;
};

export type GetTokensParams = {
  tokenIds: string[] | string;
};

export type GetTokens200ItemsItem = {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
};

export type GetTokens200 = {
  items: GetTokens200ItemsItem[];
};

export type GetTokensSearchParams = {
  /**
   * @minLength 2
   */
  query: string;
  offset?: number;
  /**
   * @maximum 100
   */
  limit?: number;
};

export type GetTokensSearch200ItemsItem = {
  id: string;
  name?: string;
  decimals: number;
  isVerified: boolean;
};

export type GetTokensSearch200 = {
  items: GetTokensSearch200ItemsItem[];
  total: number;
};

/**
 * Returns service version
 */
export const getInfoVersion = () =>
  httpClient<GetInfoVersion200>({ url: `/info/version`, method: 'GET' });

/**
 * Returns service blockchain related information
 */
export const getInfoBlockchain = () =>
  httpClient<GetInfoBlockchain200>({ url: `/info/blockchain`, method: 'GET' });

/**
 * Search over tags
 */
export const getInfoTags = (params?: GetInfoTagsParams) =>
  httpClient<string[]>({ url: `/info/tags`, method: 'GET', params });

/**
 * Returns a list of raffles
 */
export const getRaffle = (params?: GetRaffleParams) =>
  httpClient<GetRaffle200>({ url: `/raffle`, method: 'GET', params });

/**
 * Returns a single raffle by ID
 */
export const getRaffleRaffleId = (raffleId: string) =>
  httpClient<GetRaffleRaffleId200>({ url: `/raffle/${raffleId}`, method: 'GET' });

/**
 * Returns a list of baskets on specified raffle
 */
export const getRaffleRaffleIdBasket = (raffleId: string, params?: GetRaffleRaffleIdBasketParams) =>
  httpClient<GetRaffleRaffleIdBasket200>({
    url: `/raffle/${raffleId}/basket`,
    method: 'GET',
    params
  });

/**
 * Transaction for specific winner
 */
export const getRaffleRaffleIdBasketWinnerIndexTransactions = (
  raffleId: string,
  winnerIndex: number,
  params?: GetRaffleRaffleIdBasketWinnerIndexTransactionsParams
) =>
  httpClient<GetRaffleRaffleIdBasketWinnerIndexTransactions200>({
    url: `/raffle/${raffleId}/basket/${winnerIndex}/transactions`,
    method: 'GET',
    params
  });

/**
 * Returns a paginated list of user activities
 */
export const getActivity = (params?: GetActivityParams) =>
  httpClient<GetActivity200>({ url: `/activity`, method: 'GET', params });

/**
 * Returns token information for given token IDs
 */
export const getTokens = (params: GetTokensParams) =>
  httpClient<GetTokens200>({ url: `/tokens`, method: 'GET', params });

/**
 * Returns token information for given query
 */
export const getTokensSearch = (params: GetTokensSearchParams) =>
  httpClient<GetTokensSearch200>({ url: `/tokens/search`, method: 'GET', params });

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetInfoVersionResult = NonNullable<Awaited<ReturnType<typeof getInfoVersion>>>;
export type GetInfoBlockchainResult = NonNullable<Awaited<ReturnType<typeof getInfoBlockchain>>>;
export type GetInfoTagsResult = NonNullable<Awaited<ReturnType<typeof getInfoTags>>>;
export type GetRaffleResult = NonNullable<Awaited<ReturnType<typeof getRaffle>>>;
export type GetRaffleRaffleIdResult = NonNullable<Awaited<ReturnType<typeof getRaffleRaffleId>>>;
export type GetRaffleRaffleIdBasketResult = NonNullable<
  Awaited<ReturnType<typeof getRaffleRaffleIdBasket>>
>;
export type GetRaffleRaffleIdBasketWinnerIndexTransactionsResult = NonNullable<
  Awaited<ReturnType<typeof getRaffleRaffleIdBasketWinnerIndexTransactions>>
>;
export type GetActivityResult = NonNullable<Awaited<ReturnType<typeof getActivity>>>;
export type GetTokensResult = NonNullable<Awaited<ReturnType<typeof getTokens>>>;
export type GetTokensSearchResult = NonNullable<Awaited<ReturnType<typeof getTokensSearch>>>;
