/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Minimal API
 * OpenAPI spec version: 1.0.0
 */
export type GetPing200 = {
  message?: string;
};

/**
 * @summary Ping endpoint
 */
export type getPingResponse200 = {
  data: GetPing200;
  status: 200;
};

export type getPingResponseSuccess = getPingResponse200 & {
  headers: Headers;
};

export type getPingResponse = getPingResponseSuccess;

export const getGetPingUrl = () => `/ping`;

export const getPing = async (options?: RequestInit): Promise<getPingResponse> => {
  const res = await fetch(getGetPingUrl(), {
    ...options,
    method: 'GET'
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPingResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPingResponse;
};
