/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Raffle Service API
 * OpenAPI spec version: 1.0.0
 */

import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

export interface StartupResponse {
  txFee: number;
  version: string;
  verifiedTokens: VerifiedToken[];
}

export interface VerifiedToken {
  tokenId: string;
  name: string;
}

export interface InfoResponse {
  lastBlockHeight: number;
  health: string;
  /** Percentage * 10 (e.g. 30 = 3%) */
  serviceFee: number;
  /** Percentage * 10 (e.g. 20 = 2%) */
  implementerFee: number;
  creationFee: number;
}

export interface RaffleSummaryResponse {
  total: number;
  items: RaffleSummary[];
}

export type RaffleSummaryStatus = (typeof RaffleSummaryStatus)[keyof typeof RaffleSummaryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaffleSummaryStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

export interface RaffleSummary {
  raffleId: string;
  name: string;
  description?: string;
  image?: string;
  collectingTokenId: string;
  winnersCount: number;
  giftCount: number;
  tags?: string[];
  /** Unix timestamp (seconds) */
  deadline: number;
  goal: number;
  ticketPrice: number;
  soldTicketCount: number;
  status: RaffleSummaryStatus;
}

export type GetRafflesParams = {
  page?: number;
  pageSize?: number;
  status?: GetRafflesStatus;
};

export type GetRafflesStatus = (typeof GetRafflesStatus)[keyof typeof GetRafflesStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRafflesStatus = {
  active: 'active',
  successful: 'successful',
  failed: 'failed'
} as const;

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get startup configuration
 */
export type getStartupResponse200 = {
  data: StartupResponse;
  status: 200;
};

export type getStartupResponseSuccess = getStartupResponse200 & {
  headers: Headers;
};

export type getStartupResponse = getStartupResponseSuccess;

export const getGetStartupUrl = () => `/api/startup`;

export const getStartup = async (options?: RequestInit): Promise<getStartupResponse> => {
  const res = await fetch(getGetStartupUrl(), {
    ...options,
    method: 'GET'
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getStartupResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getStartupResponse;
};

export const getGetStartupQueryKey = () => [`/api/startup`] as const;

export const getGetStartupQueryOptions = <
  TData = Awaited<ReturnType<typeof getStartup>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStartup>>, TError, TData>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStartupQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStartup>>> = ({ signal }) =>
    getStartup({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStartup>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStartupQueryResult = NonNullable<Awaited<ReturnType<typeof getStartup>>>;
export type GetStartupQueryError = unknown;

/**
 * @summary Get startup configuration
 */

export function useGetStartup<
  TData = Awaited<ReturnType<typeof getStartup>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStartup>>, TError, TData>;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStartupQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get service information
 */
export type getInfoResponse200 = {
  data: InfoResponse;
  status: 200;
};

export type getInfoResponseSuccess = getInfoResponse200 & {
  headers: Headers;
};

export type getInfoResponse = getInfoResponseSuccess;

export const getGetInfoUrl = () => `/api/info`;

export const getInfo = async (options?: RequestInit): Promise<getInfoResponse> => {
  const res = await fetch(getGetInfoUrl(), {
    ...options,
    method: 'GET'
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getInfoResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getInfoResponse;
};

export const getGetInfoQueryKey = () => [`/api/info`] as const;

export const getGetInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getInfo>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInfoQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInfo>>> = ({ signal }) =>
    getInfo({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>;
export type GetInfoQueryError = unknown;

/**
 * @summary Get service information
 */

export function useGetInfo<
  TData = Awaited<ReturnType<typeof getInfo>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetInfoQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get raffle summaries
 */
export type getRafflesResponse200 = {
  data: RaffleSummaryResponse;
  status: 200;
};

export type getRafflesResponseSuccess = getRafflesResponse200 & {
  headers: Headers;
};

export type getRafflesResponse = getRafflesResponseSuccess;

export const getGetRafflesUrl = (params?: GetRafflesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/raffles?${stringifiedParams}` : `/api/raffles`;
};

export const getRaffles = async (
  params?: GetRafflesParams,
  options?: RequestInit
): Promise<getRafflesResponse> => {
  const res = await fetch(getGetRafflesUrl(params), {
    ...options,
    method: 'GET'
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRafflesResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getRafflesResponse;
};

export const getGetRafflesQueryKey = (params?: GetRafflesParams) =>
  [`/api/raffles`, ...(params ? [params] : [])] as const;

export const getGetRafflesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRaffles>>,
  TError = unknown
>(
  params?: GetRafflesParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRaffles>>, TError, TData>;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRafflesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRaffles>>> = ({ signal }) =>
    getRaffles(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRaffles>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRafflesQueryResult = NonNullable<Awaited<ReturnType<typeof getRaffles>>>;
export type GetRafflesQueryError = unknown;

/**
 * @summary Get raffle summaries
 */

export function useGetRaffles<TData = Awaited<ReturnType<typeof getRaffles>>, TError = unknown>(
  params?: GetRafflesParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRaffles>>, TError, TData>;
    fetch?: RequestInit;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRafflesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
